# GSEA Functional Enrichment Analysis for GSE253154
# MTR4 cKO vs WT in mouse spermatogonia
# NOTE: adapted from gsea_script.R provided in class (FGT tutorial, Simon Tomlinson 2026)
# Uses fgsea package with MSigDB Hallmark gene sets (mouse)

library(fgsea)
library(dplyr)
library(biomaRt)
library(ggplot2)

# Load the DESeq2 results saved from the main analysis script
# This file is generated by analysis_GSE253154.Rmd
results <- read.csv("result_GSE253154.csv", header = TRUE)
head(results)

# Load the Hallmark mouse gene sets
# File provided with course materials (mouse_H_v5p2.rdata)
# Original source: https://bioinf.wehi.edu.au/software/MSigDB/
load("mouse_H_v5p2.rdata")
head(Mm.H)

# Map Ensembl gene IDs to Entrez IDs using BiomaRt
# The MSigDB Hallmark sets use Entrez IDs
# NOTE: cache the mapping to avoid repeated downloads
if (file.exists("ens2entrez.RData")) {
  load("ens2entrez.RData")
  print("Loaded cached Ensembl-to-Entrez mapping...")
} else {
  mart <- useDataset("mmusculus_gene_ensembl", mart = useMart("ensembl"))
  ens2entrez <- getBM(attributes = c("ensembl_gene_id", "entrezgene_id"), mart = mart)
  save(ens2entrez, file = "ens2entrez.RData")
  print("Downloaded and saved Ensembl-to-Entrez mapping...")
}
head(ens2entrez)

# Join results with Entrez IDs
# NOTE: adapted from class code (FGT tutorial, Simon Tomlinson 2026)
results2 <- inner_join(results, ens2entrez, by = join_by("X" == "ensembl_gene_id"))
head(results2, n = 20)

# Remove genes with no Entrez ID mapping
results2 <- results2[is.na(results2$entrezgene_id) == FALSE, ]
cat("Genes with valid Entrez IDs:", nrow(results2), "\n")

# Order by p-value (ascending) for ranked list input to fgsea
# Using p-value ordering: genes at the top are most significantly DE
# We then log2-transform p-values to create a ranking metric
# (lower p-value = more negative log2(p), so most significant genes rank highest in magnitude)
results2 <- results2[order(results2$pvalue, decreasing = FALSE), ]
results2 <- results2[, c("pvalue", "entrezgene_id")]

# Remove duplicate Entrez IDs (keep first/most significant occurrence)
results2 <- results2[!duplicated(results2$entrezgene_id), ]
rownames(results2) <- results2[, "entrezgene_id"]
results2["entrezgene_id"] <- NULL

# Convert to named vector as required by fgsea
rn <- rownames(results2)
colnames(results2) <- NULL
results2 <- results2[, 1]
names(results2) <- rn

# Remove any NA values
results2 <- results2[!(is.na(names(results2)))]
results2 <- results2[!(is.na(results2))]

# Log2 transform p-values to create ranking metric
results2 <- log2(results2)
head(results2)
cat("Number of genes in ranked list:", length(results2), "\n")

# Run fgsea with Hallmark gene sets
# minSize=25: require at least 25 genes in a set to test it
# maxSize=500: ignore very large gene sets
# NOTE: adapted from class code (FGT tutorial, Simon Tomlinson 2026)
set.seed(42) # for reproducibility
fgseaRes <- fgsea(Mm.H, results2, minSize = 25, maxSize = 500)

# Order by Normalised Enrichment Score (NES)
fgseaRes <- fgseaRes[order(fgseaRes$NES, decreasing = FALSE), ]

cat("\nTop enriched pathways (most negative NES = depleted in cKO):\n")
print(head(fgseaRes[, c("pathway", "pval", "padj", "NES", "size")], 10))

cat("\nTop positively enriched pathways (most positive NES = enriched in cKO):\n")
print(tail(fgseaRes[, c("pathway", "pval", "padj", "NES", "size")], 10))

# Plot top enriched pathway
top_pathway <- fgseaRes$pathway[nrow(fgseaRes)]
plotEnrichment(Mm.H[[top_pathway]], results2) +
  labs(title = paste("Enrichment:", top_pathway),
       subtitle = "MTR4 cKO vs WT | GSE253154",
       x = "Gene rank", y = "Enrichment score") +
  theme_bw()

# Plot top depleted pathway
bottom_pathway <- fgseaRes$pathway[1]
plotEnrichment(Mm.H[[bottom_pathway]], results2) +
  labs(title = paste("Enrichment:", bottom_pathway),
       subtitle = "MTR4 cKO vs WT | GSE253154",
       x = "Gene rank", y = "Enrichment score") +
  theme_bw()

# Summary barplot of ALL pathways ranked by NES - extension beyond class materials
# Plotting all pathways is more informative when no pathways survive multiple
# testing correction, as it reveals the overall direction of transcriptional change
# Colour coded by significance level to distinguish strong, nominal, and ns results
# Reference: Subramanian et al. 2005 PNAS
# Git checkpoint: git commit -m "Add full GSEA barplot with biological interpretation"

fgseaRes$pathway_short <- gsub("HALLMARK_", "", fgseaRes$pathway)
fgseaRes$significance_label <- ifelse(fgseaRes$padj < 0.05, "padj < 0.05",
                               ifelse(fgseaRes$pval < 0.05, "pval < 0.05", "ns"))

ggplot(fgseaRes, aes(x = reorder(pathway_short, NES),
                     y = NES,
                     fill = significance_label)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  scale_fill_manual(
    values = c("padj < 0.05" = "#d73027",
               "pval < 0.05" = "#fc8d59",
               "ns" = "#91bfdb"),
    name = "Significance"
  ) +
  geom_hline(yintercept = 0, linetype = "dashed", colour = "black") +
  labs(
    title = "Hallmark Pathway Enrichment — MTR4 cKO vs WT",
    subtitle = "GSE253154 | All 50 Hallmark pathways ranked by NES",
    x = "Hallmark Pathway",
    y = "Normalised Enrichment Score (NES)\n(negative = depleted in cKO)"
  ) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 8),
        legend.position = "bottom")

ggsave("fgsea_hallmark_barplot_all.png", width = 11, height = 9)

# Print nominally significant pathways for discussion
cat("\nNominally significant pathways (pval < 0.05, before multiple testing):\n")
nominal_sig <- fgseaRes[fgseaRes$pval < 0.05,
                        c("pathway", "pval", "padj", "NES", "size")]
print(nominal_sig[order(nominal_sig$NES), ])

cat("\n--- INTERPRETATION ---\n")
cat("All NES values are negative, indicating broad depletion of Hallmark\n")
cat("pathways in MTR4 cKO spermatogonia relative to WT.\n")
cat("No pathways survive multiple testing correction (padj < 0.05),\n")
cat("consistent with a diffuse rather than pathway-specific effect.\n")
cat("This is consistent with MTR4 acting as a general RNA surveillance factor.\n")
cat("HALLMARK_SPERMATOGENESIS shows a trend toward depletion (NES =",
    round(fgseaRes$NES[fgseaRes$pathway == "HALLMARK_SPERMATOGENESIS"], 3),
    ") supporting the known role of MTR4 in spermatogenesis.\n")

# Save full fgsea results table
fgseaRes_out <- fgseaRes[, c("pathway", "pval", "padj", "NES", "size")]
write.csv(as.data.frame(fgseaRes_out), file = "fgsea_results_GSE253154.csv", row.names = FALSE)
cat("\nFull fgsea results saved to fgsea_results_GSE253154.csv\n")
