# GSEA Functional Enrichment Analysis for GSE253154
# MTR4 cKO vs WT in mouse spermatogonia
# NOTE: adapted from gsea_script.R provided in class (FGT tutorial, Simon Tomlinson 2026)
# Uses fgsea package with MSigDB Hallmark gene sets (mouse)

library(fgsea)
library(dplyr)
library(biomaRt)
library(ggplot2)

# Load the DESeq2 results saved from the main analysis script
# This file is generated by analysis_GSE253154.Rmd
results <- read.csv("result_GSE253154.csv", header = TRUE)
head(results)

# Load the Hallmark mouse gene sets
# File provided with course materials (mouse_H_v5p2.rdata)
# Original source: https://bioinf.wehi.edu.au/software/MSigDB/
load("mouse_H_v5p2.rdata")
head(Mm.H)

# Map Ensembl gene IDs to Entrez IDs using BiomaRt
# The MSigDB Hallmark sets use Entrez IDs
# NOTE: cache the mapping to avoid repeated downloads
if (file.exists("ens2entrez.RData")) {
  load("ens2entrez.RData")
  print("Loaded cached Ensembl-to-Entrez mapping...")
} else {
  mart <- useDataset("mmusculus_gene_ensembl", mart = useMart("ensembl"))
  ens2entrez <- getBM(attributes = c("ensembl_gene_id", "entrezgene_id"), mart = mart)
  save(ens2entrez, file = "ens2entrez.RData")
  print("Downloaded and saved Ensembl-to-Entrez mapping...")
}
head(ens2entrez)

# Join results with Entrez IDs
# NOTE: adapted from class code (FGT tutorial, Simon Tomlinson 2026)
results2 <- inner_join(results, ens2entrez, by = join_by("X" == "ensembl_gene_id"))
head(results2, n = 20)

# Remove genes with no Entrez ID mapping
results2 <- results2[is.na(results2$entrezgene_id) == FALSE, ]
cat("Genes with valid Entrez IDs:", nrow(results2), "\n")

# Order by p-value (ascending) for ranked list input to fgsea
# Using p-value ordering: genes at the top are most significantly DE
# We then log2-transform p-values to create a ranking metric
# (lower p-value = more negative log2(p), so most significant genes rank highest in magnitude)
results2 <- results2[order(results2$pvalue, decreasing = FALSE), ]
results2 <- results2[, c("pvalue", "entrezgene_id")]

# Remove duplicate Entrez IDs (keep first/most significant occurrence)
results2 <- results2[!duplicated(results2$entrezgene_id), ]
rownames(results2) <- results2[, "entrezgene_id"]
results2["entrezgene_id"] <- NULL

# Convert to named vector as required by fgsea
rn <- rownames(results2)
colnames(results2) <- NULL
results2 <- results2[, 1]
names(results2) <- rn

# Remove any NA values
results2 <- results2[!(is.na(names(results2)))]
results2 <- results2[!(is.na(results2))]

# Log2 transform p-values to create ranking metric
results2 <- log2(results2)
head(results2)
cat("Number of genes in ranked list:", length(results2), "\n")

# Run fgsea with Hallmark gene sets
# minSize=25: require at least 25 genes in a set to test it
# maxSize=500: ignore very large gene sets
# NOTE: adapted from class code (FGT tutorial, Simon Tomlinson 2026)
set.seed(42) # for reproducibility
fgseaRes <- fgsea(Mm.H, results2, minSize = 25, maxSize = 500)

# Order by Normalised Enrichment Score (NES)
fgseaRes <- fgseaRes[order(fgseaRes$NES, decreasing = FALSE), ]

cat("\nTop enriched pathways (most negative NES = depleted in cKO):\n")
print(head(fgseaRes[, c("pathway", "pval", "padj", "NES", "size")], 10))

cat("\nTop positively enriched pathways (most positive NES = enriched in cKO):\n")
print(tail(fgseaRes[, c("pathway", "pval", "padj", "NES", "size")], 10))

# Plot top enriched pathway
top_pathway <- fgseaRes$pathway[nrow(fgseaRes)]
plotEnrichment(Mm.H[[top_pathway]], results2) +
  labs(title = paste("Enrichment:", top_pathway),
       subtitle = "MTR4 cKO vs WT | GSE253154",
       x = "Gene rank", y = "Enrichment score") +
  theme_bw()

# Plot top depleted pathway
bottom_pathway <- fgseaRes$pathway[1]
plotEnrichment(Mm.H[[bottom_pathway]], results2) +
  labs(title = paste("Enrichment:", bottom_pathway),
       subtitle = "MTR4 cKO vs WT | GSE253154",
       x = "Gene rank", y = "Enrichment score") +
  theme_bw()

# Summary barplot of significant pathways (padj < 0.05)
sig_pathways <- fgseaRes[fgseaRes$padj < 0.05, ]
cat("\nNumber of significant Hallmark pathways (padj < 0.05):", nrow(sig_pathways), "\n")

if (nrow(sig_pathways) > 0) {
  sig_pathways$pathway_short <- gsub("HALLMARK_", "", sig_pathways$pathway)
  sig_pathways <- sig_pathways[order(sig_pathways$NES), ]

  ggplot(sig_pathways, aes(x = reorder(pathway_short, NES), y = NES, fill = NES > 0)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_manual(values = c("TRUE" = "#d73027", "FALSE" = "#4575b4"),
                      labels = c("TRUE" = "Enriched in cKO", "FALSE" = "Depleted in cKO")) +
    labs(
      title = "Significant Hallmark Pathways (padj < 0.05)",
      subtitle = "MTR4 cKO vs WT | GSE253154",
      x = "Hallmark Pathway",
      y = "Normalised Enrichment Score (NES)",
      fill = "Direction"
    ) +
    theme_bw() +
    theme(axis.text.y = element_text(size = 9))

  ggsave("fgsea_hallmark_barplot.png", width = 10, height = 7)
}

# Save full fgsea results table
fgseaRes_out <- fgseaRes[, c("pathway", "pval", "padj", "NES", "size")]
write.csv(as.data.frame(fgseaRes_out), file = "fgsea_results_GSE253154.csv", row.names = FALSE)
cat("\nFull fgsea results saved to fgsea_results_GSE253154.csv\n")
